# Generated by Django 4.1.3 on 2022-11-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_cnab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnab_file', models.FileField(upload_to='uploads')),
            ],
        ),
        migrations.DeleteModel(
            name='Fields',
        ),
    ]
